spring.application.name=cas-admin-portal
server.servlet.context-path=/cas-admin/api
server.port=8080
## ===============================
## = JPA / HIBERNATE
## ===============================
spring.jpa.properties.hibernate.envers.autoRegisterListeners=true
spring.jpa.properties.hibernate.envers.storeDataAtDelete=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.main.allow-bean-definition-overriding=true

#Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=2000000


spring.profiles.active=local
spring.cloud.config.import-check.enabled=false
