#############################################################
##                                                         ##
##        Spring Boot global properties for tests          ##
##                                                         ##
#############################################################

#============================================================================
# Spring Properties
#============================================================================

spring.application.name=cas-admin-portal
server.servlet.context-path=/cas-admin
server.address=0.0.0.0
server.port=8080
#spring.mvc.static-path-pattern=/ui/**
spring.profiles.active=test
logging.level.root=info
logging.level.org.springframework.web=info
security.enabled=true

logging.file.name=/usr/weblogic/Middleware/logs/CAS-ADMIN/application.log


# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.url=jdbc:oracle:thin:@dc2tst-scan.sampath.lk:1523/tcmndb
spring.datasource.username=casv2apn
spring.datasource.password=casv2apn
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#

#spring.datasource.jndi-name=CASV2APNTST2

# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.envers.autoRegisterListeners=true
spring.jpa.properties.hibernate.envers.storeDataAtDelete=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true



spring.config.import=endpoints.properties


# Required to generate Swagger UI & API docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Optional: If you have custom servlet path
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.version=OPENAPI_3_0
