#app endpoint configuration
app.endpoint.api =/api

#UPM Group
app.endpoint.upmGroupBasePath=${app.endpoint.api}/upmGroup
app.endpoint.upmGroupCreate=${app.endpoint.upmGroupBasePath}/saveUpmGroup
app.endpoint.upmGroupList=${app.endpoint.upmGroupBasePath}
app.endpoint.upmGroupView=${app.endpoint.upmGroupBasePath}/{upmGroupID}
app.endpoint.upmGroupUpdate=${app.endpoint.upmGroupBasePath}/{upmGroupID}
app.endpoint.upmGroupApproveReject=${app.endpoint.upmGroupBasePath}/approvedRejectUpmGroup
app.endpoint.upmGroupTempList=${app.endpoint.upmGroupBasePath}/upmGroupTemp
app.endpoint.upmGroupTempViewById=${app.endpoint.upmGroupBasePath}/upmGroupTemp/{upmGroupID}
app.endpoint.upmGroupTempUpdate=${app.endpoint.upmGroupBasePath}/updateUpmGroupTemp/{upmGroupID}
app.endpoint.updateUpmGroup=${app.endpoint.upmGroupBasePath}/updateUpmGroup/{upmGroupID}
app.endpoint.deleteUpmGroup=${app.endpoint.upmGroupBasePath}/deleteUpmGroup


#Role
app.endpoint.roleBasePath=${app.endpoint.api}/role
app.endpoint.privilegeList=${app.endpoint.roleBasePath}/getSystemPrivileges
app.endpoint.saveRole=${app.endpoint.roleBasePath}
app.endpoint.getRoleList=${app.endpoint.roleBasePath}
app.endpoint.viewRoleById=${app.endpoint.roleBasePath}/{roleID}
app.endpoint.roleApproveReject=${app.endpoint.roleBasePath}/approvedRejectRole
app.endpoint.updateRole=${app.endpoint.roleBasePath}/updateTempRole/{roleID}
app.endpoint.updateApprovedRole=${app.endpoint.roleBasePath}/updateApprovedRole/{roleID}
app.endpoint.roleList=${app.endpoint.roleBasePath}/searchRoles
app.endpoint.viewTempRoleById=${app.endpoint.roleBasePath}/roleTemp/{roleID}
app.endpoint.roleTempList=${app.endpoint.roleBasePath}/roleTempList
app.endpoint.deleteRoleTemp=${app.endpoint.roleBasePath}/deleteRoleTemp
app.endpoint.privileges=${app.endpoint.roleBasePath}/privileges

#User DA
app.endpoint.userDaBasePath=${app.endpoint.api}/userDa
app.endpoint.saveUserDa=${app.endpoint.userDaBasePath}
app.endpoint.viewUserDaList=${app.endpoint.userDaBasePath}/userDasList
app.endpoint.viewUserDaById=${app.endpoint.userDaBasePath}/{userDaID}
app.endpoint.updateUserDaTemp=${app.endpoint.userDaBasePath}/updateUserDaTemp/{userDaID}
app.endpoint.userDaApproveReject=${app.endpoint.userDaBasePath}/approveRejectUserDa
app.endpoint.viewUserDaTempList=${app.endpoint.userDaBasePath}/userDaTemp
app.endpoint.viewUserDaTempById=${app.endpoint.userDaBasePath}/userDaTemp/{userDaID}
app.endpoint.deleteUserDaTemp=${app.endpoint.userDaBasePath}/userDaTemp/deleteUserDaTemp
app.endpoint.updateUserDaMaster=${app.endpoint.userDaBasePath}/userDa/{userDaID}


#Supporting Document
app.endpoint.supportingDocBasePath=${app.endpoint.api}/supportingDoc
app.endpoint.saveSupportingDoc=${app.endpoint.supportingDocBasePath}
app.endpoint.viewSupportingDocList=${app.endpoint.supportingDocBasePath}/supportingDocsList
app.endpoint.viewSupportingDocById=${app.endpoint.supportingDocBasePath}/{supportingDocID}
app.endpoint.updateSupportingDocTemp=${app.endpoint.supportingDocBasePath}/updateSupportingDocTemp/{supportingDocID}
app.endpoint.supportingDocApproveReject=${app.endpoint.supportingDocBasePath}/approveRejectSupportingDoc
app.endpoint.viewSupportingDocTempList=${app.endpoint.supportingDocBasePath}/supportingDocTemp
app.endpoint.supportingDocTempViewById=${app.endpoint.supportingDocBasePath}/supportingDocTemp/{supportingDocID}
app.endpoint.deleteSupportingDocTemp=${app.endpoint.supportingDocBasePath}/supportingDocTemp/deleteSupportingDocTemp
app.endpoint.updateApprovedSupportingDoc=${app.endpoint.supportingDocBasePath}/updateApprovedSupportingDoc/{supportingDocID}

#CreditFacilityType
app.endpoint.creditFacilityTypeBasePath=${app.endpoint.api}/creditFacilityType
app.endpoint.saveCreditFacilityType=${app.endpoint.creditFacilityTypeBasePath}/saveCreditFacilityType
app.endpoint.getCreditFacilityTempTypeById=${app.endpoint.creditFacilityTypeBasePath}/getCreditFacilityTempTypeById/{creditFacilityTypeID}
app.endpoint.creditFacilityTypeApproveReject=${app.endpoint.creditFacilityTypeBasePath}/approveRejectCreditFacilityType
app.endpoint.updateCreditFacilityTempType=${app.endpoint.creditFacilityTypeBasePath}/updateCreditFacilityTempType/{creditFacilityTypeID}
app.endpoint.getCreditFacilityTypeMasterList = ${app.endpoint.creditFacilityTypeBasePath}/getCreditFacilityTypeMasterList
app.endpoint.getCreditFacilityType=${app.endpoint.creditFacilityTypeBasePath}/getCreditFacilityType/{creditFacilityTypeID}
app.endpoint.getCreditFacilityTypeTempList=${app.endpoint.creditFacilityTypeBasePath}/getCreditFacilityTypeTempList
app.endpoint.deleteCreditFacilityTypeTemp=${app.endpoint.creditFacilityTypeBasePath}/deleteCreditFacilityTypeTemp
app.endpoint.updateCreditFacilityMasterType=${app.endpoint.creditFacilityTypeBasePath}/updateCreditFacilityMasterType/{creditFacilityTypeID}

#Upc Section
app.endpoint.upcSectionBasePath=${app.endpoint.api}/upcSection
app.endpoint.saveUpcSection=${app.endpoint.upcSectionBasePath}
app.endpoint.viewUpcSectionList=${app.endpoint.upcSectionBasePath}/upcSectionList
app.endpoint.viewUpcSectionById=${app.endpoint.upcSectionBasePath}/{upcSectionID}
app.endpoint.updateUpcSectionTemp=${app.endpoint.upcSectionBasePath}/updateUpcSectionTemp/{upcSectionID}
app.endpoint.upcSectionApproveReject=${app.endpoint.upcSectionBasePath}/approveRejectUpcSection
app.endpoint.viewUpcSectionTempList=${app.endpoint.upcSectionBasePath}/upcSectionTemp
app.endpoint.viewUpcSectionTempById=${app.endpoint.upcSectionBasePath}/upcSectionTemp/{upcSectionID}
app.endpoint.deleteUpcSectionTemp=${app.endpoint.upcSectionBasePath}/upcSectionTemp/deleteUpcSectionTemp
app.endpoint.updateUpcSectionMaster=${app.endpoint.upcSectionBasePath}/updateUpcSectionMaster/{upcSectionID}

#Workflow Template
app.endpoint.workflowTemplateBasePath=${app.endpoint.api}/workflowTemplate
app.endpoint.getAllApprovedUPMGroups=${app.endpoint.workflowTemplateBasePath}/getAllApprovedUPMGroups
app.endpoint.getTempWorkflowTemplate=${app.endpoint.workflowTemplateBasePath}/getTempWorkflowTemplate
app.endpoint.getWorkflowTemplate=${app.endpoint.workflowTemplateBasePath}/getWorkflowTemplate
app.endpoint.saveOrUpdateTempWorkflowTemplate=${app.endpoint.workflowTemplateBasePath}/saveOrUpdateTempWorkflowTemplate
app.endpoint.updateWorkflowTemp=${app.endpoint.workflowTemplateBasePath}/updateTemp
app.endpoint.authorizeWorkFlowTemp=${app.endpoint.workflowTemplateBasePath}/authorizeWorkFlowTemp
app.endpoint.updateWorkFlow=${app.endpoint.workflowTemplateBasePath}/updateWorkFlow
app.endpoint.deleteWorkFlowTemp=${app.endpoint.workflowTemplateBasePath}/deleteWorkFlowTemp

app.endpoint.viewWorkflowTemplateTempList=${app.endpoint.workflowTemplateBasePath}/workflowTemplateTemp
app.endpoint.viewWorkflowTemplateList=${app.endpoint.workflowTemplateBasePath}/workflowTemplate
app.endpoint.viewWorkflowTemplateTempById = ${app.endpoint.workflowTemplateBasePath}/workflowTemplateTemp/{workflowTemplateID}

#Upc Template
app.endpoint.upcTemplateBasePath=${app.endpoint.api}/upcTemplate
app.endpoint.saveUpcTemplate=${app.endpoint.upcTemplateBasePath}
app.endpoint.updateUpcTemplate=${app.endpoint.upcTemplateBasePath}/updateUpcTemplateTemp/{upcTemplateID}
app.endpoint.approveRejectUpcTemplate=${app.endpoint.upcTemplateBasePath}/approveRejectUpcTemplate
app.endpoint.upcTemplateTempList=${app.endpoint.upcTemplateBasePath}/upcTemplateTemp/UpcTemplateTempList
app.endpoint.UpcTemplateTempById=${app.endpoint.upcTemplateBasePath}/upcTemplateTemp/UpcTemplateTempById/{upcTemplateID}
app.endpoint.updateUpcTemplateMaster=${app.endpoint.upcTemplateBasePath}/updateUpcTemplate/{upcTemplateID}
app.endpoint.findAllApprovedUpcTemplateList=${app.endpoint.upcTemplateBasePath}/upcTemplateTemp/findAllApprovedUpcTemplates
app.endpoint.findApprovedUpcTemplateById=${app.endpoint.upcTemplateBasePath}/findApprovedUpcTemplateById/{upcTemplateID}
app.endpoint.deleteUpcTemplateFromTemp=${app.endpoint.upcTemplateBasePath}/upcTemplateTemp/deleteUpcTemplateFromTemp


#CreditFacilityTemplate
app.endpoint.creditFacilityTemplatesBasePath=${app.endpoint.api}/creditFacilityTemplates
app.endpoint.getAllCftTemp=${app.endpoint.creditFacilityTemplatesBasePath}/getAllCftTemp
app.endpoint.getCftTempById=${app.endpoint.creditFacilityTemplatesBasePath}/getCftTempById/{creditFacilityTemplateID}
app.endpoint.getAllCftMaster=${app.endpoint.creditFacilityTemplatesBasePath}/getAllCft
app.endpoint.getCftById=${app.endpoint.creditFacilityTemplatesBasePath}/getCftById/{creditFacilityTemplateID}
app.endpoint.saveAndUpdateCftTemp=${app.endpoint.creditFacilityTemplatesBasePath}/saveAndUpdateCftTemp
app.endpoint.authorizeCft=${app.endpoint.creditFacilityTemplatesBasePath}/authorizeCft
app.endpoint.updateCft=${app.endpoint.creditFacilityTemplatesBasePath}/updateCft/{creditFacilityTemplateID}
app.endpoint.submitCft=${app.endpoint.creditFacilityTemplatesBasePath}/submitCft
app.endpoint.deleteCftTemp=${app.endpoint.creditFacilityTemplatesBasePath}/deleteCftTemp
app.endpoint.updateCftTemp=${app.endpoint.creditFacilityTemplatesBasePath}/updateCftTemp/{creditFacilityTemplateID}

#Committee Type
app.endpoint.committeeTypePath=${app.endpoint.api}/committeeType
app.endpoint.getCommitteeType=${app.endpoint.committeeTypePath}/getCommitteeType
app.endpoint.saveCommitteeType=${app.endpoint.committeeTypePath}/saveCommitteeType
app.endpoint.updateCommitteeType=${app.endpoint.committeeTypePath}/updateCommitteeType/{committeeTypeId}

#Committee Pool
app.endpoint.committeePoolPath=${app.endpoint.api}/committeePool
app.endpoint.getTempCommitteePool=${app.endpoint.committeePoolPath}/getTempCommitteePool
app.endpoint.getCommitteePool=${app.endpoint.committeePoolPath}/getCommitteePool
app.endpoint.savePoolUsers=${app.endpoint.committeePoolPath}/savePoolUsers
app.endpoint.saveTempPoolUser=${app.endpoint.committeePoolPath}/saveTempPoolUser
app.endpoint.approveRejectCommitteePool=${app.endpoint.committeePoolPath}/approveRejectCommitteePool