-- Auto-generated from entity classes under src/main/java/lk/sampath/casadminportalms/entity
-- Generated on 2026-06-23

CREATE TABLE CA_COMMITTEE_TYPE_CONFIG (
    COMMITTEE_TYPE_ID NUMBER(10) NOT NULL,
    COMMITTEE_TYPE VARCHAR2(255 CHAR),
    COMMITTEE_TYPE_DESCRIPTION VARCHAR2(255 CHAR),
    CREATED_BY VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_USER_DISPLAY_NAME VARCHAR2(255 CHAR),
    AUTHORIZER_DISPLAY_NAME VARCHAR2(255 CHAR),
    STATUS VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    VERSION NUMBER(10),
    IS_SYSTEM NUMBER(10),
    CONSTRAINT PK_CA_COMMITTEE_TYPE_CONFIG PRIMARY KEY (COMMITTEE_TYPE_ID)
);

CREATE TABLE T_CFT_CUSTOM_FACILITY_INFO (
    CUSTOM_FACILITY_INFO_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    CUSTOM_FACILITY_INFO_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    CUSTOM_FACILITY_INFO_CODE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(255 CHAR),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_CUSTOM_FACILITY_INFO PRIMARY KEY (CUSTOM_FACILITY_INFO_ID)
);

CREATE TABLE T_CFT_CUSTOM_FACILITY_INFO_AUD (
    ID NUMBER(10) NOT NULL,
    CUSTOM_FACILITY_INFO_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    CUSTOM_FACILITY_INFO_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    CUSTOM_FACILITY_INFO_CODE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(255 CHAR),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_CUSTOM_FACILITY_INFO_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CFT_CUSTOM_FACILITY_INFO_TEMP (
    CUSTOM_FACILITY_INFO_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    CUSTOM_FACILITY_INFO_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    CUSTOM_FACILITY_INFO_CODE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(255 CHAR),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_CUSTOM_FACILITY_INFO_TEMP PRIMARY KEY (CUSTOM_FACILITY_INFO_ID)
);

CREATE TABLE T_CFT_INTEREST_RATE (
    CFT_INTEREST_RATE_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    RATE_NAME VARCHAR2(255 CHAR),
    RATE_CODE VARCHAR2(255 CHAR),
    VALUE NUMBER(19,4),
    IS_DEFAULT VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    INTEREST_RATING_SUB_CATEGORY VARCHAR2(50 CHAR),
    IS_EDITABLE VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_INTEREST_RATE PRIMARY KEY (CFT_INTEREST_RATE_ID)
);

CREATE TABLE T_CFT_INTEREST_RATE_AUD (
    ID NUMBER(10) NOT NULL,
    CFT_INTEREST_RATE_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    RATE_NAME VARCHAR2(255 CHAR),
    RATE_CODE VARCHAR2(255 CHAR),
    VALUE NUMBER(19,4),
    IS_DEFAULT VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    INTEREST_RATING_SUB_CATEGORY VARCHAR2(50 CHAR),
    IS_EDITABLE VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_INTEREST_RATE_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CFT_INTEREST_RATE_TEMP (
    CFT_INTEREST_RATE_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    RATE_NAME VARCHAR2(255 CHAR),
    RATE_CODE VARCHAR2(255 CHAR),
    VALUE NUMBER(19,4),
    IS_DEFAULT VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    INTEREST_RATING_SUB_CATEGORY VARCHAR2(50 CHAR),
    IS_EDITABLE VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_INTEREST_RATE_TEMP PRIMARY KEY (CFT_INTEREST_RATE_ID)
);

CREATE TABLE T_CFT_OTHER_FACILITY_INFO (
    OTHER_FACILITY_INFO_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    OTHER_FACILITY_INFO_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    OTHER_FACILITY_INFO_CODE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(50 CHAR),
    DEFAULT_VALUE VARCHAR2(255 CHAR),
    DISPLAY_ORDER NUMBER(10),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_OTHER_FACILITY_INFO PRIMARY KEY (OTHER_FACILITY_INFO_ID)
);

CREATE TABLE T_CFT_OTHER_FACILITY_INFO_AUD (
    ID NUMBER(10) NOT NULL,
    OTHER_FACILITY_INFO_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    OTHER_FACILITY_INFO_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    OTHER_FACILITY_INFO_CODE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(50 CHAR),
    DEFAULT_VALUE VARCHAR2(255 CHAR),
    DISPLAY_ORDER NUMBER(10),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_OTHER_FACILITY_INFO_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CFT_OTHER_FACILITY_INFO_TEMP (
    OTHER_FACILITY_INFO_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    OTHER_FACILITY_INFO_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    OTHER_FACILITY_INFO_CODE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(50 CHAR),
    DEFAULT_VALUE VARCHAR2(255 CHAR),
    DISPLAY_ORDER NUMBER(10),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_OTHER_FACILITY_INFO_TEMP PRIMARY KEY (OTHER_FACILITY_INFO_ID)
);

CREATE TABLE T_CFT_SUPPORTING_DOC (
    CFT_SUPPORTING_DOC_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    SUPPORTING_DOC_ID NUMBER(10),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_SUPPORTING_DOC PRIMARY KEY (CFT_SUPPORTING_DOC_ID)
);

CREATE TABLE T_CFT_SUPPORTING_DOC_AUD (
    ID NUMBER(10) NOT NULL,
    CFT_SUPPORTING_DOC_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    SUPPORTING_DOC_ID NUMBER(10),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_SUPPORTING_DOC_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CFT_SUPPORTING_DOC_TEMP (
    CFT_SUPPORTING_DOC_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    SUPPORTING_DOC_ID NUMBER(10),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_SUPPORTING_DOC_TEMP PRIMARY KEY (CFT_SUPPORTING_DOC_ID)
);

CREATE TABLE T_CFT_VITAL_INFO (
    CFT_VITAL_INFO_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    VITAL_INFO_NAME VARCHAR2(255 CHAR),
    MANDATORY VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_VITAL_INFO PRIMARY KEY (CFT_VITAL_INFO_ID)
);

CREATE TABLE T_CFT_VITAL_INFO_AUD (
    ID NUMBER(10) NOT NULL,
    CFT_VITAL_INFO_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    VITAL_INFO_NAME VARCHAR2(255 CHAR),
    MANDATORY VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_VITAL_INFO_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CFT_VITAL_INFO_TEMP (
    CFT_VITAL_INFO_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    VITAL_INFO_NAME VARCHAR2(255 CHAR),
    MANDATORY VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_VITAL_INFO_TEMP PRIMARY KEY (CFT_VITAL_INFO_ID)
);

CREATE TABLE T_COMMITTEE_POOL (
    COMMITTEE_POOL_ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10),
    USER_NAME VARCHAR2(255 CHAR),
    USER_DISPLAY_NAME VARCHAR2(255 CHAR),
    DESIGNATION VARCHAR2(255 CHAR),
    WORK_CLASS VARCHAR2(255 CHAR),
    STATUS NUMBER(10),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_COMMITTEE_POOL PRIMARY KEY (COMMITTEE_POOL_ID)
);

CREATE TABLE T_COMMITTEE_POOL_AUD (
    COMMITTEE_POOL_ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10),
    USER_NAME VARCHAR2(255 CHAR),
    USER_DISPLAY_NAME VARCHAR2(255 CHAR),
    DESIGNATION VARCHAR2(255 CHAR),
    WORK_CLASS VARCHAR2(255 CHAR),
    STATUS NUMBER(10),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_COMMITTEE_POOL_AUD PRIMARY KEY (COMMITTEE_POOL_ID)
);

CREATE TABLE T_COMMITTEE_POOL_TEMP (
    COMMITTEE_POOL_ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10),
    USER_NAME VARCHAR2(255 CHAR),
    USER_DISPLAY_NAME VARCHAR2(255 CHAR),
    DESIGNATION VARCHAR2(255 CHAR),
    WORK_CLASS VARCHAR2(255 CHAR),
    STATUS NUMBER(10),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_COMMITTEE_POOL_TEMP PRIMARY KEY (COMMITTEE_POOL_ID)
);

CREATE TABLE T_CREDIT_FACILITY_TEMPLATE (
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TYPE_ID NUMBER(10),
    CREDIT_FACILITY_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    MAXIMUM_FACILITY_AMOUNT NUMBER(19,2),
    MINIMUM_FACILITY_AMOUNT NUMBER(19,2),
    SHOW_PURPOSE VARCHAR2(50 CHAR),
    SHOW_REPAYMENT VARCHAR2(50 CHAR),
    SHOW_CONDITION VARCHAR2(50 CHAR),
    SHOW_REMARK VARCHAR2(50 CHAR),
    SHOW_CALCULATOR VARCHAR2(50 CHAR),
    SHOW_RENTAL_DATA VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    NEW_FACILITY_EMAIL VARCHAR2(255 CHAR),
    EXISTING_FACILITY_EMAIL VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CREDIT_FACILITY_TEMPLATE PRIMARY KEY (CREDIT_FACILITY_TEMPLATE_ID)
);

CREATE TABLE T_CREDIT_FACILITY_TEMPLATE_AUD (
    ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    CREDIT_FACILITY_TYPE_ID NUMBER(10),
    CREDIT_FACILITY_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    MAXIMUM_FACILITY_AMOUNT NUMBER(19,2),
    MINIMUM_FACILITY_AMOUNT NUMBER(19,2),
    SHOW_PURPOSE VARCHAR2(50 CHAR),
    SHOW_REPAYMENT VARCHAR2(50 CHAR),
    SHOW_CONDITION VARCHAR2(50 CHAR),
    SHOW_REMARK VARCHAR2(50 CHAR),
    SHOW_CALCULATOR VARCHAR2(50 CHAR),
    SHOW_RENTAL_DATA VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    NEW_FACILITY_EMAIL VARCHAR2(255 CHAR),
    EXISTING_FACILITY_EMAIL VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CREDIT_FACILITY_TEMPLATE_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CREDIT_FACILITY_TEMPLATE_TEMP (
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TYPE_ID NUMBER(10),
    CREDIT_FACILITY_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    MAXIMUM_FACILITY_AMOUNT NUMBER(19,2),
    MINIMUM_FACILITY_AMOUNT NUMBER(19,2),
    SHOW_PURPOSE VARCHAR2(50 CHAR),
    SHOW_REPAYMENT VARCHAR2(50 CHAR),
    SHOW_CONDITION VARCHAR2(50 CHAR),
    SHOW_REMARK VARCHAR2(50 CHAR),
    SHOW_CALCULATOR VARCHAR2(50 CHAR),
    SHOW_RENTAL_DATA VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    NEW_FACILITY_EMAIL VARCHAR2(255 CHAR),
    EXISTING_FACILITY_EMAIL VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CREDIT_FACILITY_TEMPLATE_TEMP PRIMARY KEY (CREDIT_FACILITY_TEMPLATE_ID)
);

CREATE TABLE T_CREDIT_FACILITY_TYPE (
    CREDIT_FACILITY_TYPE_ID NUMBER(10) NOT NULL,
    FACILITY_TYPE_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CREDIT_FACILITY_TYPE PRIMARY KEY (CREDIT_FACILITY_TYPE_ID)
);

CREATE TABLE T_CREDIT_FACILITY_TYPE_AUD (
    ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TYPE_ID NUMBER(10),
    FACILITY_TYPE_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CREDIT_FACILITY_TYPE_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CREDIT_FACILITY_TYPE_TEMP (
    CREDIT_FACILITY_TYPE_ID NUMBER(10) NOT NULL,
    FACILITY_TYPE_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CREDIT_FACILITY_TYPE_TEMP PRIMARY KEY (CREDIT_FACILITY_TYPE_ID)
);

CREATE TABLE T_FACILITY_DOCUMENT_ELEMENT (
    ELEMENT_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_TEMP_ID NUMBER(10),
    CREDIT_FACILITY_NAME VARCHAR2(255 CHAR),
    PARENT_ID NUMBER(10),
    ELEMENT_NAME VARCHAR2(255 CHAR),
    ELEMENT_TYPE VARCHAR2(255 CHAR),
    FACILITY_TYPE_ID NUMBER(10),
    IS_NEW VARCHAR2(255 CHAR),
    DOCUMENT_CONTENT VARCHAR2(255 CHAR),
    KEY VARCHAR2(255 CHAR),
    STATUS VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_FACILITY_DOCUMENT_ELEMENT PRIMARY KEY (ELEMENT_ID)
);

CREATE TABLE T_FACILITY_SECURITY_DOCUMENT (
    SECURITY_DOCUMENT_ID NUMBER(10) NOT NULL,
    ELEMENT_ID NUMBER(10),
    FACILITY_PAPER_ID NUMBER(10),
    FACILITY_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    CREDIT_FACILITY_NAME VARCHAR2(255 CHAR),
    DOCUMENT_NAME VARCHAR2(255 CHAR),
    DOCUMENT_CONTENT VARCHAR2(255 CHAR),
    SAVED_BY VARCHAR2(255 CHAR),
    PRINTED_BY VARCHAR2(255 CHAR),
    SAVED_BY_DIV VARCHAR2(255 CHAR),
    AUTH_BY_DIV VARCHAR2(255 CHAR),
    SAVED_DATE TIMESTAMP,
    PRINTED_DATE TIMESTAMP,
    RETURN_COMMENT VARCHAR2(255 CHAR),
    AUTH_BY VARCHAR2(255 CHAR),
    AUTH_DATE TIMESTAMP,
    PRINTED_BY_DIV VARCHAR2(255 CHAR),
    SAVED_BY_DISPLAY_NAME VARCHAR2(255 CHAR),
    AUTH_BY_DISPLAY_NAME VARCHAR2(255 CHAR),
    PRINTED_BY_DISPLAY_NAME VARCHAR2(255 CHAR),
    DOCUMENT_STATUS VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_FACILITY_SECURITY_DOCUMENT PRIMARY KEY (SECURITY_DOCUMENT_ID)
);

CREATE TABLE T_PRIVILEGE (
    PRIVILEGE_ID NUMBER(10) NOT NULL,
    PRIVILEGE_NAME VARCHAR2(255 CHAR),
    PRIVILEGE_CODE VARCHAR2(255 CHAR),
    BEHAVIOUR_DESCRIPTION VARCHAR2(255 CHAR),
    PRIVILEGE_CATEGORY_ID NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    CONSTRAINT PK_T_PRIVILEGE PRIMARY KEY (PRIVILEGE_ID)
);

CREATE TABLE T_PRIVILEGE_CATEGORY (
    PRIVILEGE_CATEGORY_ID NUMBER(10) NOT NULL,
    CATEGORY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_PRIVILEGE_CATEGORY PRIMARY KEY (PRIVILEGE_CATEGORY_ID)
);

CREATE TABLE T_ROLE (
    ROLE_ID NUMBER(10) NOT NULL,
    ROLE_NAME VARCHAR2(255 CHAR),
    UPM_PRIVILAGE_CODE VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_ROLE PRIMARY KEY (ROLE_ID)
);

CREATE TABLE T_ROLE_PRIVILEGE (
    ROLE_ID NUMBER(10) NOT NULL,
    PRIVILEGE_ID NUMBER(10) NOT NULL,
    CONSTRAINT PK_T_ROLE_PRIVILEGE PRIMARY KEY (ROLE_ID, PRIVILEGE_ID)
);

CREATE TABLE T_ROLE_PRIVILEGE_AUD (
    ID NUMBER(10) NOT NULL,
    ROLE_AUD_ID NUMBER(10) NOT NULL,
    PRIVILEGE_ID NUMBER(10) NOT NULL,
    ACTION_DATE TIMESTAMP NOT NULL,
    CONSTRAINT PK_T_ROLE_PRIVILEGE_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_ROLE_PRIVILEGE_TEMP (
    ROLE_ID NUMBER(10) NOT NULL,
    PRIVILEGE_ID NUMBER(10) NOT NULL,
    CONSTRAINT PK_T_ROLE_PRIVILEGE_TEMP PRIMARY KEY (ROLE_ID, PRIVILEGE_ID)
);

CREATE TABLE T_ROLE_TEMP (
    ROLE_ID NUMBER(10) NOT NULL,
    ROLE_NAME VARCHAR2(255 CHAR),
    UPM_PRIVILAGE_CODE VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_ROLE_TEMP PRIMARY KEY (ROLE_ID)
);

CREATE TABLE T_ROLES_AUD (
    ID NUMBER(10) NOT NULL,
    ROLE_ID NUMBER(10) NOT NULL,
    ROLE_NAME VARCHAR2(255 CHAR),
    UPM_PRIVILAGE_CODE VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_ROLES_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_SECURITY_DOCUMENT_TAG_DATA (
    TAG_ID NUMBER(10) NOT NULL,
    SECURITY_DOCUMENT_ID NUMBER(10),
    TAG_ORDER NUMBER(10),
    TAG VARCHAR2(255 CHAR),
    TAG_VALUE VARCHAR2(255 CHAR),
    TAG_TYPE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_SECURITY_DOCUMENT_TAG_DATA PRIMARY KEY (TAG_ID)
);

CREATE TABLE T_SUPPORTING_DOC (
    SUPPORTING_DOC_ID NUMBER(10) NOT NULL,
    DOCUMENT_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    SUPPORT_DOCUMENT_TYPE VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_SUPPORTING_DOC PRIMARY KEY (SUPPORTING_DOC_ID)
);

CREATE TABLE T_SUPPORTING_DOC_AUD (
    ID NUMBER(10) NOT NULL,
    SUPPORTING_DOC_ID NUMBER(10) NOT NULL,
    DOCUMENT_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    SUPPORT_DOCUMENT_TYPE VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_SUPPORTING_DOC_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_SUPPORTING_DOC_TEMP (
    SUPPORTING_DOC_ID NUMBER(10) NOT NULL,
    DOCUMENT_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    SUPPORT_DOCUMENT_TYPE VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_SUPPORTING_DOC_TEMP PRIMARY KEY (SUPPORTING_DOC_ID)
);

CREATE TABLE T_UPC_SECTION (
    UPC_SECTION_ID NUMBER(10) NOT NULL,
    UPC_SECTION_NAME VARCHAR2(255 CHAR),
    UPC_SECTION_DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPC_SECTION PRIMARY KEY (UPC_SECTION_ID)
);

CREATE TABLE T_UPC_SECTION_AUD (
    ID NUMBER(10) NOT NULL,
    UPC_SECTION_ID NUMBER(10) NOT NULL,
    UPC_SECTION_NAME VARCHAR2(255 CHAR),
    UPC_SECTION_DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPC_SECTION_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_UPC_SECTION_TEMP (
    UPC_SECTION_ID NUMBER(10) NOT NULL,
    UPC_SECTION_NAME VARCHAR2(255 CHAR),
    UPC_SECTION_DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPC_SECTION_TEMP PRIMARY KEY (UPC_SECTION_ID)
);

CREATE TABLE T_UPC_TEMPLATE (
    UPC_TEMPLATE_ID NUMBER(10) NOT NULL,
    TEMPLATE_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    UPC_LABEL VARCHAR2(255 CHAR),
    UPC_LABEL_BACKGROUND_COLOR VARCHAR2(255 CHAR),
    UPC_LABEL_FONT_COLOR VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPC_TEMPLATE PRIMARY KEY (UPC_TEMPLATE_ID)
);

CREATE TABLE T_UPC_TEMPLATE_AUD (
    ID NUMBER(10) NOT NULL,
    UPC_TEMPLATE_ID NUMBER(10),
    TEMPLATE_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    UPC_LABEL VARCHAR2(255 CHAR),
    UPC_LABEL_BACKGROUND_COLOR VARCHAR2(255 CHAR),
    UPC_LABEL_FONT_COLOR VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    ACTION_BY VARCHAR2(255 CHAR),
    ACTION_DATE TIMESTAMP,
    ACTION_MSG VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPC_TEMPLATE_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_UPC_TEMPLATE_DATA (
    UPC_TEMPLATE_DATA_ID NUMBER(10) NOT NULL,
    UPC_TEMPLATE_ID NUMBER(10),
    UPC_SECTION_ID NUMBER(10),
    PARENT_SECTION_ID NUMBER(10),
    SECTION_LEVEL NUMBER(10),
    DISPLAY_ORDER NUMBER(10),
    CONSTRAINT PK_T_UPC_TEMPLATE_DATA PRIMARY KEY (UPC_TEMPLATE_DATA_ID)
);

CREATE TABLE T_UPC_TEMPLATE_DATA_AUD (
    ID NUMBER(10) NOT NULL,
    UPC_TEMPLATE_DATA_ID NUMBER(10),
    UPC_TEMPLATE_ID NUMBER(10),
    UPC_SECTION_ID NUMBER(10),
    PARENT_SECTION_ID NUMBER(10),
    SECTION_LEVEL NUMBER(10),
    DISPLAY_ORDER NUMBER(10),
    CONSTRAINT PK_T_UPC_TEMPLATE_DATA_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_UPC_TEMPLATE_DATA_TEMP (
    UPC_TEMPLATE_DATA_ID NUMBER(10) NOT NULL,
    UPC_TEMPLATE_ID NUMBER(10),
    UPC_SECTION_ID NUMBER(10),
    PARENT_SECTION_ID NUMBER(10),
    SECTION_LEVEL NUMBER(10),
    DISPLAY_ORDER NUMBER(10),
    CONSTRAINT PK_T_UPC_TEMPLATE_DATA_TEMP PRIMARY KEY (UPC_TEMPLATE_DATA_ID)
);

CREATE TABLE T_UPC_TEMPLATE_TEMP (
    UPC_TEMPLATE_ID NUMBER(10) NOT NULL,
    TEMPLATE_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    UPC_LABEL VARCHAR2(255 CHAR),
    UPC_LABEL_BACKGROUND_COLOR VARCHAR2(255 CHAR),
    UPC_LABEL_FONT_COLOR VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPC_TEMPLATE_TEMP PRIMARY KEY (UPC_TEMPLATE_ID)
);

CREATE TABLE T_UPM_GROUP (
    UPM_GROUP_ID NUMBER(10) NOT NULL,
    GROUP_CODE VARCHAR2(255 CHAR),
    REFERENCE_NAME VARCHAR2(255 CHAR),
    WORK_FLOW_LEVEL NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPM_GROUP PRIMARY KEY (UPM_GROUP_ID)
);

CREATE TABLE T_UPM_GROUP_TEMP (
    UPM_GROUP_ID NUMBER(10) NOT NULL,
    GROUP_CODE VARCHAR2(255 CHAR),
    REFERENCE_NAME VARCHAR2(255 CHAR),
    WORK_FLOW_LEVEL NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPM_GROUP_TEMP PRIMARY KEY (UPM_GROUP_ID)
);

CREATE TABLE T_UPM_GROUP_TEMP_AUD (
    REV NUMBER(10) NOT NULL,
    REVTYPE NUMBER(10) NOT NULL,
    UPM_GROUP_ID NUMBER(10) NOT NULL,
    GROUP_CODE VARCHAR2(255 CHAR),
    REFERENCE_NAME VARCHAR2(255 CHAR),
    WORK_FLOW_LEVEL NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPM_GROUP_TEMP_AUD PRIMARY KEY (REV)
);

CREATE TABLE T_USER_DA (
    USER_DA_ID NUMBER(10) NOT NULL,
    USER_NAME VARCHAR2(255 CHAR),
    MAX_AMOUNT NUMBER(19,2),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_USER_DA PRIMARY KEY (USER_DA_ID)
);

CREATE TABLE T_USER_DA_AUD (
    ID NUMBER(10) NOT NULL,
    USER_DA_ID NUMBER(10) NOT NULL,
    USER_NAME VARCHAR2(255 CHAR),
    MAX_AMOUNT NUMBER(19,2),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_USER_DA_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_USER_DA_TEMP (
    USER_DA_ID NUMBER(10) NOT NULL,
    USER_NAME VARCHAR2(255 CHAR),
    MAX_AMOUNT NUMBER(19,2),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_USER_DA_TEMP PRIMARY KEY (USER_DA_ID)
);

CREATE TABLE T_WORK_FLOW_TEMPLATE (
    WORK_FLOW_TEMPLATE_ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_NAME VARCHAR2(255 CHAR),
    CODE VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_WORK_FLOW_TEMPLATE PRIMARY KEY (WORK_FLOW_TEMPLATE_ID)
);

CREATE TABLE T_WORK_FLOW_TEMPLATE_DATA (
    WORK_FLOW_TEMPLATE_DATA_ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_ID NUMBER(10),
    UPM_GROUP_ID NUMBER(10),
    NEXT_UPM_GROUP_ID NUMBER(10),
    PREVIOUS_UPM_GROUP_ID NUMBER(10),
    DISPLAY_ORDER NUMBER(10),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_WORK_FLOW_TEMPLATE_DATA PRIMARY KEY (WORK_FLOW_TEMPLATE_DATA_ID)
);

CREATE TABLE T_WORK_FLOW_TEMPLATE_DATA_AUD (
    ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_DATA_ID NUMBER(10),
    NEXT_UPM_GROUP_ID NUMBER(10),
    PREVIOUS_UPM_GROUP_ID NUMBER(10),
    UPM_GROUP_ID NUMBER(10),
    WORK_FLOW_TEMPLATE_ID NUMBER(10),
    DISPLAY_ORDER NUMBER(10),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_WORK_FLOW_TEMPLATE_DATA_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_WORK_FLOW_TEMPLATE_DATA_TEMP (
    WORK_FLOW_TEMPLATE_DATA_ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_ID NUMBER(10),
    UPM_GROUP_ID NUMBER(10),
    NEXT_UPM_GROUP_ID NUMBER(10),
    PREVIOUS_UPM_GROUP_ID NUMBER(10),
    DISPLAY_ORDER NUMBER(10),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_WORK_FLOW_TEMPLATE_DATA_TEMP PRIMARY KEY (WORK_FLOW_TEMPLATE_DATA_ID)
);

CREATE TABLE T_WORK_FLOW_TEMPLATE_TEMP (
    WORK_FLOW_TEMPLATE_ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_NAME VARCHAR2(255 CHAR),
    CODE VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_WORK_FLOW_TEMPLATE_TEMP PRIMARY KEY (WORK_FLOW_TEMPLATE_ID)
);

CREATE TABLE T_WORKFLOW_TEMPLATE_AUD (
    ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_NAME VARCHAR2(255 CHAR),
    CODE VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_WORKFLOW_TEMPLATE_AUD PRIMARY KEY (ID)
);


================================================================================================================================================
=============================================================     NEW    =======================================================================
================================================================================================================================================

--------------------------
/*-- 1. UPC_SECTION --*/
--------------------------
CREATE SEQUENCE CASV3_SEQ_UPC_SECTION_AUD INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999999999999 MINVALUE 1 NOCACHE;

CREATE TABLE CASV3_T_UPC_SECTION_AUD AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_UPC_SECTION t
WHERE 1 = 0;

CREATE TABLE CASV3_T_UPC_SECTION_TEMP AS
SELECT *
FROM T_UPC_SECTION
WHERE 1 = 0;

INSERT INTO CASV3_T_UPC_SECTION_AUD
SELECT
    CASV3_SEQ_UPC_SECTION_AUD.NEXTVAL AS ID,
    t.*
FROM T_UPC_SECTION t;


ALTER TABLE CASV3_T_UPC_SECTION_AUD
ADD CONSTRAINT PK_CASV3_UPC_SECTION_AUD
PRIMARY KEY (ID);

DELETE FROM T_UPC_SECTION s
WHERE (s.approve_status <> 'APPROVED'
   OR s.status <> 'ACT')
AND NOT EXISTS (
    SELECT 1
    FROM T_FP_UPC_SECTION_DATA d
    WHERE d.UPC_SECTION_ID = s.UPC_SECTION_ID
)
AND NOT EXISTS (
    SELECT 1
    FROM T_UPC_TEMPLATE_DATA t
    WHERE t.UPC_SECTION_ID = s.UPC_SECTION_ID
);

-----------------------------------
/*-- 1. CREDIT FACILITY TYPE --*/
----------------------------------

CREATE SEQUENCE CASV3_SEQ_FACILITY_TYPE_AUD INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999999999999 MINVALUE 1 NOCACHE;

CREATE TABLE CASV3_T_CREDIT_FACILITY_TYPE_AUD AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_CREDIT_FACILITY_TYPE t
WHERE 1 = 0;

CREATE TABLE CASV3_T_CREDIT_FACILITY_TYPE_TEMP AS
SELECT *
FROM T_CREDIT_FACILITY_TYPE
WHERE 1 = 0;


INSERT INTO CASV3_T_CREDIT_FACILITY_TYPE_AUD
SELECT
    CASV3_SEQ_FACILITY_TYPE_AUD.NEXTVAL,
    t.*
FROM T_CREDIT_FACILITY_TYPE t;


ALTER TABLE CASV3_T_CREDIT_FACILITY_TYPE_AUD
ADD CONSTRAINT PK_CASV3_FAC_TYPE_AUD
PRIMARY KEY (ID);

DELETE FROM T_CREDIT_FACILITY_TYPE s
WHERE (s.approve_status <> 'APPROVED'
   OR s.status <> 'ACT');


---------------------------------------
/*-- 1. CREDIT FACILITY TEMPLATE --*/
---------------------------------------
---1----
CREATE SEQUENCE CASV3_SEQ_CREDIT_FACILITY_TEMPLATE_AUD INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999999999999 MINVALUE 1 NOCACHE;

---2----
CREATE TABLE CASV3_T_CREDIT_FACILITY_TEMPLATE_AUD AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_CREDIT_FACILITY_TEMPLATE t
WHERE 1 = 0;

CREATE TABLE CASV3_T_CREDIT_FACILITY_TEMPLATE_TEMP AS
SELECT *
FROM T_CREDIT_FACILITY_TEMPLATE
WHERE 1 = 0;

---3----
INSERT INTO CASV3_T_CREDIT_FACILITY_TEMPLATE_AUD
SELECT
    CASV3_SEQ_CREDIT_FACILITY_TEMPLATE_AUD.NEXTVAL,
    t.*
FROM T_CREDIT_FACILITY_TEMPLATE t;

---4----
ALTER TABLE CASV3_T_CREDIT_FACILITY_TEMPLATE_AUD
ADD CONSTRAINT PK_CASV3_FAC_TEMPLATE_AUD
PRIMARY KEY (ID);

---5----
DELETE FROM T_CREDIT_FACILITY_TEMPLATE s
WHERE (s.approve_status <> 'APPROVED'
   OR s.status <> 'ACT')

AND NOT EXISTS (
    SELECT 1
    FROM T_CFT_VITAL_INFO d
    WHERE D.CREDIT_FACILITY_TEMPLATE_ID = s.CREDIT_FACILITY_TEMPLATE_ID
)

AND NOT EXISTS (
    SELECT 1
    FROM T_CFT_INTEREST_RATE t
    WHERE t.CREDIT_FACILITY_TEMPLATE_ID = s.CREDIT_FACILITY_TEMPLATE_ID
)

AND NOT EXISTS (
    SELECT 1
    FROM T_FACILITY d
    WHERE D.CREDIT_FACILITY_TEMPLATE_ID = s.CREDIT_FACILITY_TEMPLATE_ID
)

AND NOT EXISTS (
    SELECT 1
    FROM T_CFT_SUPPORTING_DOC d
    WHERE D.CREDIT_FACILITY_TEMPLATE_ID = s.CREDIT_FACILITY_TEMPLATE_ID
)

AND NOT EXISTS (
    SELECT 1
    FROM T_CFT_OTHER_FACILITY_INFO d
    WHERE D.CREDIT_FACILITY_TEMPLATE_ID = s.CREDIT_FACILITY_TEMPLATE_ID
)

AND NOT EXISTS (
    SELECT 1
    FROM T_AF_FACILITY d
    WHERE D.CREDIT_FACILITY_TEMPLATE_ID = s.CREDIT_FACILITY_TEMPLATE_ID
);


----- CFT VITAL INFO ----
CREATE SEQUENCE CASV3_SEQ_CFT_VITAL_INFO_AUD INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999999999999 MINVALUE 1 NOCACHE;

CREATE TABLE CASV3_T_CFT_VITAL_INFO_AUD AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_CFT_VITAL_INFO t
WHERE 1 = 0;

CREATE TABLE CASV3_T_CFT_VITAL_INFO_TEMP AS
SELECT *
FROM T_CFT_VITAL_INFO
WHERE 1 = 0;

INSERT INTO CASV3_T_CFT_VITAL_INFO_AUD
SELECT
    CASV3_SEQ_CFT_VITAL_INFO_AUD.NEXTVAL,
    t.*
FROM T_CFT_VITAL_INFO t;


ALTER TABLE CASV3_T_CFT_VITAL_INFO_AUD
ADD CONSTRAINT PK_CASV3_CFT_VITAL_INFO_AUD
PRIMARY KEY (ID);

ALTER TABLE T_CFT_VITAL_INFO ADD RECORD_STATUS VARCHAR2(20);
ALTER TABLE CASV3_T_CFT_VITAL_INFO_AUD ADD RECORD_STATUS VARCHAR2(20);
ALTER TABLE CASV3_T_CFT_VITAL_INFO_TEMP ADD RECORD_STATUS VARCHAR2(20);


DELETE FROM T_CFT_VITAL_INFO s
WHERE s.status <> 'ACT';

----- CFT INTEREST RATE ----

CREATE SEQUENCE CASV3_SEQ_CFT_INTEREST_RATE_AUD INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999999999999 MINVALUE 1 NOCACHE;

CREATE TABLE CASV3_T_CFT_INTEREST_RATE_AUD AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_CFT_INTEREST_RATE t
WHERE 1 = 0;

CREATE TABLE CASV3_T_CFT_INTEREST_RATE_TEMP AS
SELECT *
FROM T_CFT_INTEREST_RATE
WHERE 1 = 0;

INSERT INTO CASV3_T_CFT_INTEREST_RATE_AUD
SELECT
    CASV3_SEQ_CFT_INTEREST_RATE_AUD.NEXTVAL,
    t.*
FROM T_CFT_INTEREST_RATE t;


ALTER TABLE CASV3_T_CFT_INTEREST_RATE_AUD
ADD CONSTRAINT PK_CASV3_CFT_INTEREST_RATE_AUD
PRIMARY KEY (ID);

ALTER TABLE T_CFT_INTEREST_RATE ADD RECORD_STATUS VARCHAR2(20);
ALTER TABLE CASV3_T_CFT_INTEREST_RATE_AUD ADD RECORD_STATUS VARCHAR2(20);
ALTER TABLE CASV3_T_CFT_INTEREST_RATE_TEMP ADD RECORD_STATUS VARCHAR2(20);

DELETE FROM T_CFT_INTEREST_RATE s
WHERE s.status <> 'ACT';


----- CFT SUPPORTING DOC ----

CREATE SEQUENCE CASV3_SEQ_CFT_SUPPORTING_DOC INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999999999999 MINVALUE 1 NOCACHE;

CREATE TABLE CASV3_T_CFT_SUPPORTING_DOC_AUD AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_CFT_SUPPORTING_DOC t
WHERE 1 = 0;

CREATE TABLE CASV3_T_CFT_SUPPORTING_DOC_TEMP AS
SELECT *
FROM T_CFT_SUPPORTING_DOC
WHERE 1 = 0;

INSERT INTO CASV3_T_CFT_SUPPORTING_DOC_AUD
SELECT
    CASV3_SEQ_CFT_SUPPORTING_DOC.NEXTVAL,
    t.*
FROM T_CFT_SUPPORTING_DOC t;


ALTER TABLE CASV3_T_CFT_SUPPORTING_DOC_AUD
ADD CONSTRAINT PK_CASV3_CFT_SUPPORTING_DOC_AUD
PRIMARY KEY (ID);

ALTER TABLE T_CFT_SUPPORTING_DOC ADD RECORD_STATUS VARCHAR2(20);
ALTER TABLE CASV3_T_CFT_SUPPORTING_DOC_AUD ADD RECORD_STATUS VARCHAR2(20);
ALTER TABLE CASV3_T_CFT_SUPPORTING_DOC_TEMP ADD RECORD_STATUS VARCHAR2(20);

DELETE FROM T_CFT_SUPPORTING_DOC s
WHERE s.status <> 'ACT';


----- CFT OTHER FACILITY INFO ----

CREATE SEQUENCE CASV3_SEQ_CFT_OTHER_FACILITY_INFO_AUD INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999999999999 MINVALUE 1 NOCACHE;

CREATE TABLE CASV3_T_CFT_OTHER_FACILITY_INFO_AUD AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_CFT_OTHER_FACILITY_INFO t
WHERE 1 = 0;

CREATE TABLE CASV3_T_CFT_OTHER_FACILITY_INFO_TEMP AS
SELECT *
FROM T_CFT_OTHER_FACILITY_INFO
WHERE 1 = 0;

INSERT INTO CASV3_T_CFT_OTHER_FACILITY_INFO_AUD
SELECT
    CASV3_SEQ_CFT_OTHER_FACILITY_INFO_AUD.NEXTVAL,
    t.*
FROM T_CFT_OTHER_FACILITY_INFO t;


ALTER TABLE CASV3_T_CFT_OTHER_FACILITY_INFO_AUD
ADD CONSTRAINT PK_CASV3_CFT_OTHER_FACILITY_INFO_AUD
PRIMARY KEY (ID);

ALTER TABLE T_CFT_OTHER_FACILITY_INFO ADD RECORD_STATUS VARCHAR2(20);
ALTER TABLE CASV3_T_CFT_OTHER_FACILITY_INFO_AUD ADD RECORD_STATUS VARCHAR2(20);
ALTER TABLE CASV3_T_CFT_OTHER_FACILITY_INFO_TEMP ADD RECORD_STATUS VARCHAR2(20);

DELETE FROM T_CFT_OTHER_FACILITY_INFO s
WHERE s.status <> 'ACT';


----- CFT CUSTOM FACILITY INFO ----

CREATE SEQUENCE CASV3_SEQ_CFT_CUSTOM_FACILITY_INFO_AUD INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999999999999 MINVALUE 1 NOCACHE;

CREATE TABLE CASV3_T_CFT_CUSTOM_FACILITY_INFO_AUD AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_CFT_CUSTOM_FACILITY_INFO t
WHERE 1 = 0;

CREATE TABLE CASV3_T_CFT_CUSTOM_FACILITY_INFO_TEMP AS
SELECT *
FROM T_CFT_CUSTOM_FACILITY_INFO
WHERE 1 = 0;

INSERT INTO CASV3_T_CFT_CUSTOM_FACILITY_INFO_AUD
SELECT
    CASV3_SEQ_CFT_CUSTOM_FACILITY_INFO_AUD.NEXTVAL,
    t.*
FROM T_CFT_CUSTOM_FACILITY_INFO t;


ALTER TABLE CASV3_T_CFT_CUSTOM_FACILITY_INFO_AUD
ADD CONSTRAINT PK_CASV3_CFT_CUSTOM_FACILITY_INFO_AUD
PRIMARY KEY (ID);

ALTER TABLE T_CFT_CUSTOM_FACILITY_INFO ADD RECORD_STATUS VARCHAR2(20);
ALTER TABLE CASV3_T_CFT_CUSTOM_FACILITY_INFO_AUD ADD RECORD_STATUS VARCHAR2(20);
ALTER TABLE CASV3_T_CFT_CUSTOM_FACILITY_INFO_TEMP ADD RECORD_STATUS VARCHAR2(20);

DELETE FROM T_CFT_CUSTOM_FACILITY_INFO s
WHERE s.status <> 'ACT';


-----------------------------------
/*-- 1. SUPPORTING DOCUMENT --*/
----------------------------------
---1----
CREATE SEQUENCE CASV3_SEQ_SUPPORTING_DOC_AUD INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999999999 MINVALUE 1 NOCACHE;

---2----
CREATE TABLE CASV3_T_SUPPORTING_DOC_AUD AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_SUPPORTING_DOC t
WHERE 1 = 0;

CREATE TABLE CASV3_T_SUPPORTING_DOC_TEMP AS
SELECT *
FROM T_SUPPORTING_DOC
WHERE 1 = 0;

---3----
INSERT INTO CASV3_T_SUPPORTING_DOC_AUD
SELECT
    CASV3_SEQ_SUPPORTING_DOC_AUD.NEXTVAL,
    t.*
FROM T_SUPPORTING_DOC t;

---4----
ALTER TABLE CASV3_T_SUPPORTING_DOC_AUD
ADD CONSTRAINT PK_CASV3_SUPPORTING_DOC_AUD
PRIMARY KEY (ID);

---5----
DELETE FROM T_SUPPORTING_DOC s
WHERE (s.approve_status <> 'APPROVED'
   OR s.status <> 'ACT')


-----------------------------------
/*-- 1. UPC Template --*/
-----------------------------------

---1----
CREATE SEQUENCE CASV3_SEQ_UPC_TEMPLATE_AUD INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE CASV3_SEQ_UPC_TEMPLATE_DATA_AUD INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999999999 MINVALUE 1 NOCACHE;

---2----
CREATE TABLE CASV3_T_UPC_TEMPLATE_AUD AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_UPC_TEMPLATE t
WHERE 1 = 0;

CREATE TABLE CASV3_T_UPC_TEMPLATE_TEMP AS
SELECT *
FROM T_UPC_TEMPLATE
WHERE 1 = 0;

CREATE TABLE CASV3_T_UPC_TEMPLATE_DATA_AUD AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_UPC_TEMPLATE_DATA t
WHERE 1 = 0;

CREATE TABLE CASV3_T_UPC_TEMPLATE_DATA_TEMP AS
SELECT *
FROM T_UPC_TEMPLATE_DATA
WHERE 1 = 0;

---3----
INSERT INTO CASV3_T_UPC_TEMPLATE_AUD
SELECT
    CASV3_SEQ_UPC_TEMPLATE_AUD.NEXTVAL,
    t.*
FROM T_UPC_TEMPLATE t;

INSERT INTO CASV3_T_UPC_TEMPLATE_DATA_AUD
SELECT
    CASV3_SEQ_UPC_TEMPLATE_DATA_AUD.NEXTVAL,
    t.*
FROM T_UPC_TEMPLATE_DATA t;

---4----
ALTER TABLE CASV3_T_UPC_TEMPLATE_AUD
ADD CONSTRAINT PK_CASV3_UPC_TEMPLATE_AUD
PRIMARY KEY (ID);

ALTER TABLE CASV3_T_UPC_TEMPLATE_DATA_AUD
ADD CONSTRAINT PK_CASV3_UPC_TEMPLATE_DATA_AUD
PRIMARY KEY (ID);

ALTER TABLE CASV3_T_UPC_TEMPLATE_AUD
ADD (
    ACTION_MSG  VARCHAR2(500),
    ACTION_BY   VARCHAR2(100),
    ACTION_DATE DATE
);

---5----
DELETE FROM T_UPC_TEMPLATE_DATA d
WHERE EXISTS (
    SELECT 1
    FROM T_UPC_TEMPLATE t
    WHERE t.UPC_TEMPLATE_ID = d.UPC_TEMPLATE_ID
      AND (t.APPROVE_STATUS <> 'APPROVED'
           OR t.STATUS <> 'ACT')
);

DELETE FROM T_UPC_TEMPLATE t
WHERE t.APPROVE_STATUS <> 'APPROVED'
   OR t.STATUS <> 'ACT';


-----------------------------------
/*-- 1. Deviation --*/
-----------------------------------
CREATE SEQUENCE CASV3_SEQ_DEVIATIONS_AUD INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999999999999 MINVALUE 1 NOCACHE;

ALTER TABLE T_DEVIATIONS_TEMP ADD (
    MODIFIED_DATE   DATE,
    MODIFIED_BY     VARCHAR2(100),
    APPROVE_STATUS  VARCHAR2(50),
    APPROVED_DATE   DATE,
    APPROVED_BY     VARCHAR2(100)
);

ALTER TABLE T_DEVIATIONS ADD(
    APPROVED_DATE   DATE,
    APPROVED_BY     VARCHAR2(100)
);

ALTER TABLE T_DEVIATIONS_AUD ADD (
    ID NUMBER(10) NOT NULL,
    APPROVE_STATUS  VARCHAR2(50),
    APPROVED_DATE   DATE,
    APPROVED_BY     VARCHAR2(100)
);

ALTER TABLE T_DEVIATIONS_TEMP MODIFY (PARENT_ID NULL);

CREATE TABLE CASV3_T_DEVIATIONS_AUDIT AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_DEVIATIONS t
WHERE 1 = 0;

---3----
INSERT INTO CASV3_T_DEVIATIONS_AUDIT
SELECT
    CASV3_SEQ_DEVIATIONS_AUD.NEXTVAL,
    t.*
FROM T_DEVIATIONS t;


--------------------------
/*-- USER DA --*/
--------------------------

---1----
CREATE SEQUENCE CASV3_SEQ_USER_DA_AUD INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999999999999 MINVALUE 1 NOCACHE;

---1----
CREATE TABLE CASV3_T_USER_DA_AUD AS
SELECT
    CAST(NULL AS NUMBER) AS ID,
    t.*
FROM T_USER_DA t
WHERE 1 = 0;

---2----
ALTER TABLE CASV3_T_USER_DA_AUD
MODIFY CLEAN_AMOUNT DEFAULT 0;

---3----
INSERT INTO CASV3_T_USER_DA_AUD
SELECT
    CASV3_SEQ_USER_DA_AUD.NEXTVAL,
    t.*
FROM T_USER_DA t;

---4----
ALTER TABLE CASV3_T_USER_DA_AUD
ADD CONSTRAINT PK_CASV3_USER_DA_AUD
PRIMARY KEY (ID);

---5----
DELETE FROM T_USER_DA s
WHERE (s.approve_status <> 'APPROVED'
   OR s.status <> 'ACT');

---6----
CREATE TABLE CASV3_T_USER_DA_TEMP AS
SELECT *
FROM T_USER_DA
WHERE 1 = 0;

---7----
ALTER TABLE CASV3_T_USER_DA_TEMP
MODIFY CLEAN_AMOUNT DEFAULT 0;


--------------------------
/*-- Roles --*/
--------------------------

CREATE TABLE CASV3_T_ROLE_TEMP (
                                   ROLE_ID            NUMBER(10)       NOT NULL,
                                   ROLE_NAME          VARCHAR2(255),
                                   UPM_PRIVILAGE_CODE VARCHAR2(255),
                                   STATUS             VARCHAR2(50),
                                   CREATED_BY         VARCHAR2(100),
                                   CREATED_DATE       TIMESTAMP,
                                   MODIFIED_BY        VARCHAR2(100),
                                   MODIFIED_DATE      TIMESTAMP,
                                   APPROVED_BY        VARCHAR2(100),
                                   APPROVED_DATE      TIMESTAMP,
                                   APPROVE_STATUS     VARCHAR2(20),
                                   CONSTRAINT PK_CASV3_T_ROLE_TEMP PRIMARY KEY (ROLE_ID)
);


CREATE TABLE CASV3_T_ROLE_PRIVILEGE_TEMP (
                                       ROLE_ID NUMBER(10) NOT NULL,
                                       PRIVILEGE_ID NUMBER(10) NOT NULL,
                                       CONSTRAINT PK_CASV3_T_ROLE_PRIVILEGE_TEMP PRIMARY KEY (ROLE_ID, PRIVILEGE_ID)
);


CREATE SEQUENCE  "SEQ_T_ROLES_AUD"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2542 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  "SEQ_T_ROLE_PRIVILEGE_AUD"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2542 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE TABLE CASV3_T_ROLE_AUD (
                                  ROLE_AUD_ID         NUMBER(10)     NOT NULL,
                                  ROLE_ID             NUMBER(10)     NOT NULL,
                                  ROLE_NAME           VARCHAR2(255),
                                  UPM_PRIVILAGE_CODE  VARCHAR2(50),
                                  STATUS              VARCHAR2(50),
                                  APPROVE_STATUS       VARCHAR2(50),

                                  CREATED_BY          VARCHAR2(100),
                                  CREATED_DATE        TIMESTAMP,
                                  MODIFIED_BY         VARCHAR2(100),
                                  MODIFIED_DATE       TIMESTAMP,
                                  APPROVED_BY         VARCHAR2(100),
                                  APPROVED_DATE       TIMESTAMP,

                                  CONSTRAINT PK_CASV3_T_ROLE_AUD
                                      PRIMARY KEY (ROLE_AUD_ID)
);


CREATE TABLE CASV3_T_ROLE_PRIVILEGE_AUD (
                                            ID            NUMBER(10)      NOT NULL,
                                            ROLE_AUD_ID   NUMBER(10)      NOT NULL,
                                            PRIVILEGE_ID  NUMBER(10)      NOT NULL,
                                            ACTION_DATE   TIMESTAMP       NOT NULL,

                                            CONSTRAINT PK_T_ROLE_PRIVILEGE_AUD
                                                PRIMARY KEY (ID)
);

--------------------------
/*-- Workflow Template --*/
--------------------------

CREATE TABLE CASV3_T_WORK_FLOW_TEMPLATE_TEMP
(
    WORK_FLOW_TEMPLATE_ID    NUMBER(10,0),
    WORK_FLOW_TEMPLATE_NAME  VARCHAR2(255 BYTE),
    CODE                     VARCHAR2(255 BYTE),
    DESCRIPTION              VARCHAR2(255 BYTE),
    STATUS                   CHAR(3 BYTE),
    APPROVED_DATE            DATE,
    APPROVED_BY              VARCHAR2(50 BYTE),
    PARENT_REC_ID            NUMBER(10,0),
    CREATED_DATE             DATE,
    CREATED_BY               VARCHAR2(50 BYTE),
    MODIFIED_DATE            DATE,
    MODIFIED_BY              VARCHAR2(50 BYTE),
    VERSION                  NUMBER(10,0),
    APPROVE_STATUS           VARCHAR2(20 BYTE),
     CONSTRAINT PK_CASV3_T_WORK_FLOW_TEMPLATE_TEMP
                                                PRIMARY KEY (WORK_FLOW_TEMPLATE_ID)
);



CREATE TABLE CASV3_T_WORK_FLOW_TEMPLATE_DATA_TEMP (
                                                      WORK_FLOW_TEMPLATE_DATA_TEMP_ID INT NOT NULL,
                                                      WORK_FLOW_TEMPLATE_ID INT,
                                                      UPM_GROUP_ID INT,
                                                      NEXT_UPM_GROUP_ID INT,
                                                      PREVIOUS_UPM_GROUP_ID INT,
                                                      DISPLAY_ORDER INT,
                                                      PRIMARY KEY(WORK_FLOW_TEMPLATE_DATA_TEMP_ID)
);


CREATE SEQUENCE  "CASV3_SEQ_WORKFLOW_TEMP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 68 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "CASV3_SEQ_WORKFLOW_DATA_TEMP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 68 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  "CASV3_SEQ_T_WORKFLOW"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 68 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "CASV3_SEQ_T_WORKFLOW_AUD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 68 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "CASV3_SEQ_T_WORKFLOW_DATA_AUD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 68 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE TABLE CASV3_T_WORKFLOW_TEMPLATE_AUD (
                                               ID NUMBER(10) NOT NULL,
                                               WORK_FLOW_TEMPLATE_ID NUMBER(10) NOT NULL,
                                               WORK_FLOW_TEMPLATE_NAME VARCHAR2(255),
                                               CODE VARCHAR2(255),
                                               DESCRIPTION VARCHAR2(4000),
                                               STATUS VARCHAR2(50),

                                               APPROVE_STATUS  VARCHAR2(100),
                                               CREATED_BY VARCHAR2(100),
                                               CREATED_DATE TIMESTAMP,
                                               MODIFIED_BY VARCHAR2(100),
                                               MODIFIED_DATE TIMESTAMP,
                                               APPROVED_BY VARCHAR2(100),
                                               APPROVED_DATE TIMESTAMP,

                                               CONSTRAINT PK_T_WORKFLOW_TEMPLATE_AUD
                                                   PRIMARY KEY (ID)
);


CREATE TABLE CASV3_T_WORK_FLOW_TEMPLATE_DATA_AUD (
                                                      ID NUMBER(10) NOT NULL,
                                                      WORK_FLOW_TEMPLATE_DATA_ID INT NOT NULL,
                                                      WORK_FLOW_TEMPLATE_ID INT,
                                                      UPM_GROUP_ID INT,
                                                      NEXT_UPM_GROUP_ID INT,
                                                      PREVIOUS_UPM_GROUP_ID INT,
                                                      DISPLAY_ORDER INT,
                                                      PRIMARY KEY(ID)
);

-----------------------------------
/*-- 1. DA Designation --*/
-----------------------------------

CREATE TABLE CASV3_T_DA_TABLE_HEADER (
    ID NUMBER(10) PRIMARY KEY,
    TABLE_TYPE VARCHAR2(30) NOT NULL,
    PARENT_ID NUMBER(10),
    LABEL VARCHAR2(200) NOT NULL,
    LEVEL_NO NUMBER(2) NOT NULL,
    DISPLAY_ORDER NUMBER(5) NOT NULL,
    COL_SPAN NUMBER(3),
    ROW_SPAN NUMBER(3),
    SUB_ID NUMBER(5)
);

INSERT ALL

/* LEVEL 1 */

INTO CASV3_T_DA_TABLE_HEADER
(ID,TABLE_TYPE,PARENT_ID,LABEL,LEVEL_NO,DISPLAY_ORDER,COL_SPAN,ROW_SPAN,SUB_ID)
VALUES (1,'INDIVIDUAL',NULL,'FACILITY',1,1,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (2,'INDIVIDUAL',NULL,'SECURITY TYPE',1,2,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (3,'INDIVIDUAL',NULL,'COLUMN NO',1,3,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (4,'INDIVIDUAL',NULL,'BORROWER RISK GRADING',1,4,1,1,NULL)

/* LEVEL 2 - FACILITY */

INTO CASV3_T_DA_TABLE_HEADER
VALUES (5,'INDIVIDUAL',1,'DIRECT/INDIRECT REGULAR FACILITIES',2,1,9,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (6,'INDIVIDUAL',1,'CLEAN',2,2,2,2,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (7,'INDIVIDUAL',1,'VEHICLE LEASING',2,3,2,2,NULL)

/* LEVEL 2 - SECURITY TYPE */

INTO CASV3_T_DA_TABLE_HEADER
VALUES (8,'INDIVIDUAL',2,'1st CLASS',2,1,3,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (9,'INDIVIDUAL',2,'OTHER',2,2,3,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (10,'INDIVIDUAL',2,'TOTAL LIMIT',2,3,3,1,NULL)

/* LEVEL 2 - COLUMN NO */

INTO CASV3_T_DA_TABLE_HEADER
VALUES (11,'INDIVIDUAL',3,'A',2,1,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (12,'INDIVIDUAL',3,'B',2,2,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (13,'INDIVIDUAL',3,'C',2,3,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (14,'INDIVIDUAL',3,'D',2,4,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (15,'INDIVIDUAL',3,'E',2,5,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (16,'INDIVIDUAL',3,'F',2,6,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (17,'INDIVIDUAL',3,'G (A to F)',2,7,3,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (18,'INDIVIDUAL',3,'H',2,8,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (19,'INDIVIDUAL',3,'I',2,9,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (20,'INDIVIDUAL',3,'J',2,10,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (21,'INDIVIDUAL',3,'K',2,11,1,1,NULL)

/* LEVEL 2 - BORROWER RISK GRADING */

INTO CASV3_T_DA_TABLE_HEADER
VALUES (22,'INDIVIDUAL',4,'B and above',2,1,1,1,1)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (23,'INDIVIDUAL',4,'B-/C+',2,2,1,1,2)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (24,'INDIVIDUAL',4,'C/C-',2,3,1,1,3)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (25,'INDIVIDUAL',4,'B and above',2,4,1,1,4)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (26,'INDIVIDUAL',4,'B-/C+',2,5,1,1,5)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (27,'INDIVIDUAL',4,'C/C-',2,6,1,1,6)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (28,'INDIVIDUAL',4,'B and above',2,7,1,1,7)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (29,'INDIVIDUAL',4,'B-/C+',2,8,1,1,8)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (30,'INDIVIDUAL',4,'C/C-',2,9,1,1,9)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (31,'INDIVIDUAL',4,'C+ and Above',2,10,1,1,10)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (32,'INDIVIDUAL',4,'C/C-',2,11,1,1,11)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (33,'INDIVIDUAL',4,'C+ and Above',2,12,1,1,12)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (34,'INDIVIDUAL',4,'C/C-',2,13,1,1,13)

SELECT * FROM DUAL;




INSERT ALL

/* LEVEL 1 */

INTO CASV3_T_DA_TABLE_HEADER
(ID,TABLE_TYPE,PARENT_ID,LABEL,LEVEL_NO,DISPLAY_ORDER,COL_SPAN,ROW_SPAN,SUB_ID)
VALUES (35,'COMMITTEE',NULL,'SECURITY TYPE',1,1,1,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (36,'COMMITTEE',NULL,'BORROWER RISK GRADING',1,2,1,1,NULL)

/* LEVEL 2 - SECURITY TYPE */

INTO CASV3_T_DA_TABLE_HEADER
VALUES (37,'COMMITTEE',35,'1st CLASS',2,1,3,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (38,'COMMITTEE',35,'OTHER SECURITIES (SUB-LIMIT)',2,2,3,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (39,'COMMITTEE',35,'CLEAN',2,3,3,1,NULL)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (40,'COMMITTEE',35,'TOTAL FACILITY',2,4,3,1,NULL)

/* LEVEL 2 - BORROWER RISK GRADING */

INTO CASV3_T_DA_TABLE_HEADER
VALUES (41,'COMMITTEE',36,'A+ to A-',2,1,1,1,1)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (42,'COMMITTEE',36,'B+ to B-',2,2,1,1,2)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (43,'COMMITTEE',36,'C+ to C-',2,3,1,1,3)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (44,'COMMITTEE',36,'A+ to A-',2,4,1,1,4)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (45,'COMMITTEE',36,'B+ to B-',2,5,1,1,5)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (46,'COMMITTEE',36,'C+ to C-',2,6,1,1,6)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (47,'COMMITTEE',36,'A+ to A-',2,7,1,1,7)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (48,'COMMITTEE',36,'B+ to B-',2,8,1,1,8)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (49,'COMMITTEE',36,'C+ to C-',2,9,1,1,9)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (50,'COMMITTEE',36,'A+ to A-',2,10,1,1,10)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (51,'COMMITTEE',36,'B+ to B-',2,11,1,1,11)

INTO CASV3_T_DA_TABLE_HEADER
VALUES (52,'COMMITTEE',36,'C+ to C-',2,12,1,1,12)

SELECT * FROM DUAL;

-----------------------------------
/* DA Limit Audit */
-----------------------------------

CREATE SEQUENCE CASV3_SEQ_DA_LIMIT_AUD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CASV3_T_DA_LIMIT_AUD (
    ID NUMBER(10) NOT NULL,
    DA_LIMITS_ID NUMBER(10) NOT NULL,
    DESIGNATION_ID NUMBER(10),
    COLUMN_ID NUMBER(10),
    RISK_VALUE NUMBER(19,4),
    STATUS VARCHAR2(50 CHAR),
    AUTHORIZER_DISPLAY_NAME VARCHAR2(255 CHAR),
    RISK_RATING VARCHAR2(255 CHAR),
    IS_COMMITTEE VARCHAR2(5 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_CASV3_T_DA_LIMIT_AUD PRIMARY KEY (ID)
);
