-- Auto-generated from entity classes under src/main/java/lk/sampath/casadminportalms/entity
-- Generated on 2026-06-23

CREATE TABLE CA_COMMITTEE_TYPE_CONFIG (
    COMMITTEE_TYPE_ID NUMBER(10) NOT NULL,
    COMMITTEE_TYPE VARCHAR2(255 CHAR),
    COMMITTEE_TYPE_DESCRIPTION VARCHAR2(255 CHAR),
    CREATED_BY VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_USER_DISPLAY_NAME VARCHAR2(255 CHAR),
    AUTHORIZER_DISPLAY_NAME VARCHAR2(255 CHAR),
    STATUS VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    VERSION NUMBER(10),
    IS_SYSTEM NUMBER(10),
    CONSTRAINT PK_CA_COMMITTEE_TYPE_CONFIG PRIMARY KEY (COMMITTEE_TYPE_ID)
);

CREATE TABLE T_CFT_CUSTOM_FACILITY_INFO (
    CUSTOM_FACILITY_INFO_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    CUSTOM_FACILITY_INFO_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    CUSTOM_FACILITY_INFO_CODE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(255 CHAR),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_CUSTOM_FACILITY_INFO PRIMARY KEY (CUSTOM_FACILITY_INFO_ID)
);

CREATE TABLE T_CFT_CUSTOM_FACILITY_INFO_AUD (
    ID NUMBER(10) NOT NULL,
    CUSTOM_FACILITY_INFO_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    CUSTOM_FACILITY_INFO_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    CUSTOM_FACILITY_INFO_CODE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(255 CHAR),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_CUSTOM_FACILITY_INFO_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CFT_CUSTOM_FACILITY_INFO_TEMP (
    CUSTOM_FACILITY_INFO_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    CUSTOM_FACILITY_INFO_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    CUSTOM_FACILITY_INFO_CODE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(255 CHAR),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_CUSTOM_FACILITY_INFO_TEMP PRIMARY KEY (CUSTOM_FACILITY_INFO_ID)
);

CREATE TABLE T_CFT_INTEREST_RATE (
    CFT_INTEREST_RATE_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    RATE_NAME VARCHAR2(255 CHAR),
    RATE_CODE VARCHAR2(255 CHAR),
    VALUE NUMBER(19,4),
    IS_DEFAULT VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    INTEREST_RATING_SUB_CATEGORY VARCHAR2(50 CHAR),
    IS_EDITABLE VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_INTEREST_RATE PRIMARY KEY (CFT_INTEREST_RATE_ID)
);

CREATE TABLE T_CFT_INTEREST_RATE_AUD (
    ID NUMBER(10) NOT NULL,
    CFT_INTEREST_RATE_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    RATE_NAME VARCHAR2(255 CHAR),
    RATE_CODE VARCHAR2(255 CHAR),
    VALUE NUMBER(19,4),
    IS_DEFAULT VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    INTEREST_RATING_SUB_CATEGORY VARCHAR2(50 CHAR),
    IS_EDITABLE VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_INTEREST_RATE_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CFT_INTEREST_RATE_TEMP (
    CFT_INTEREST_RATE_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    RATE_NAME VARCHAR2(255 CHAR),
    RATE_CODE VARCHAR2(255 CHAR),
    VALUE NUMBER(19,4),
    IS_DEFAULT VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    INTEREST_RATING_SUB_CATEGORY VARCHAR2(50 CHAR),
    IS_EDITABLE VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_INTEREST_RATE_TEMP PRIMARY KEY (CFT_INTEREST_RATE_ID)
);

CREATE TABLE T_CFT_OTHER_FACILITY_INFO (
    OTHER_FACILITY_INFO_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    OTHER_FACILITY_INFO_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    OTHER_FACILITY_INFO_CODE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(50 CHAR),
    DEFAULT_VALUE VARCHAR2(255 CHAR),
    DISPLAY_ORDER NUMBER(10),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_OTHER_FACILITY_INFO PRIMARY KEY (OTHER_FACILITY_INFO_ID)
);

CREATE TABLE T_CFT_OTHER_FACILITY_INFO_AUD (
    ID NUMBER(10) NOT NULL,
    OTHER_FACILITY_INFO_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    OTHER_FACILITY_INFO_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    OTHER_FACILITY_INFO_CODE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(50 CHAR),
    DEFAULT_VALUE VARCHAR2(255 CHAR),
    DISPLAY_ORDER NUMBER(10),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_OTHER_FACILITY_INFO_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CFT_OTHER_FACILITY_INFO_TEMP (
    OTHER_FACILITY_INFO_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    OTHER_FACILITY_INFO_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    OTHER_FACILITY_INFO_CODE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(50 CHAR),
    DEFAULT_VALUE VARCHAR2(255 CHAR),
    DISPLAY_ORDER NUMBER(10),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_OTHER_FACILITY_INFO_TEMP PRIMARY KEY (OTHER_FACILITY_INFO_ID)
);

CREATE TABLE T_CFT_SUPPORTING_DOC (
    CFT_SUPPORTING_DOC_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    SUPPORTING_DOC_ID NUMBER(10),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_SUPPORTING_DOC PRIMARY KEY (CFT_SUPPORTING_DOC_ID)
);

CREATE TABLE T_CFT_SUPPORTING_DOC_AUD (
    ID NUMBER(10) NOT NULL,
    CFT_SUPPORTING_DOC_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    SUPPORTING_DOC_ID NUMBER(10),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_SUPPORTING_DOC_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CFT_SUPPORTING_DOC_TEMP (
    CFT_SUPPORTING_DOC_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    SUPPORTING_DOC_ID NUMBER(10),
    MANDATORY VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_SUPPORTING_DOC_TEMP PRIMARY KEY (CFT_SUPPORTING_DOC_ID)
);

CREATE TABLE T_CFT_VITAL_INFO (
    CFT_VITAL_INFO_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    VITAL_INFO_NAME VARCHAR2(255 CHAR),
    MANDATORY VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_VITAL_INFO PRIMARY KEY (CFT_VITAL_INFO_ID)
);

CREATE TABLE T_CFT_VITAL_INFO_AUD (
    ID NUMBER(10) NOT NULL,
    CFT_VITAL_INFO_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    VITAL_INFO_NAME VARCHAR2(255 CHAR),
    MANDATORY VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_VITAL_INFO_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CFT_VITAL_INFO_TEMP (
    CFT_VITAL_INFO_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    VITAL_INFO_NAME VARCHAR2(255 CHAR),
    MANDATORY VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    RECORD_STATUS VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CFT_VITAL_INFO_TEMP PRIMARY KEY (CFT_VITAL_INFO_ID)
);

CREATE TABLE T_COMMITTEE_POOL (
    COMMITTEE_POOL_ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10),
    USER_NAME VARCHAR2(255 CHAR),
    USER_DISPLAY_NAME VARCHAR2(255 CHAR),
    DESIGNATION VARCHAR2(255 CHAR),
    WORK_CLASS VARCHAR2(255 CHAR),
    STATUS NUMBER(10),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_COMMITTEE_POOL PRIMARY KEY (COMMITTEE_POOL_ID)
);

CREATE TABLE T_COMMITTEE_POOL_AUD (
    COMMITTEE_POOL_ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10),
    USER_NAME VARCHAR2(255 CHAR),
    USER_DISPLAY_NAME VARCHAR2(255 CHAR),
    DESIGNATION VARCHAR2(255 CHAR),
    WORK_CLASS VARCHAR2(255 CHAR),
    STATUS NUMBER(10),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_COMMITTEE_POOL_AUD PRIMARY KEY (COMMITTEE_POOL_ID)
);

CREATE TABLE T_COMMITTEE_POOL_TEMP (
    COMMITTEE_POOL_ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10),
    USER_NAME VARCHAR2(255 CHAR),
    USER_DISPLAY_NAME VARCHAR2(255 CHAR),
    DESIGNATION VARCHAR2(255 CHAR),
    WORK_CLASS VARCHAR2(255 CHAR),
    STATUS NUMBER(10),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_COMMITTEE_POOL_TEMP PRIMARY KEY (COMMITTEE_POOL_ID)
);

CREATE TABLE T_CREDIT_FACILITY_TEMPLATE (
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TYPE_ID NUMBER(10),
    CREDIT_FACILITY_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    MAXIMUM_FACILITY_AMOUNT NUMBER(19,2),
    MINIMUM_FACILITY_AMOUNT NUMBER(19,2),
    SHOW_PURPOSE VARCHAR2(50 CHAR),
    SHOW_REPAYMENT VARCHAR2(50 CHAR),
    SHOW_CONDITION VARCHAR2(50 CHAR),
    SHOW_REMARK VARCHAR2(50 CHAR),
    SHOW_CALCULATOR VARCHAR2(50 CHAR),
    SHOW_RENTAL_DATA VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    NEW_FACILITY_EMAIL VARCHAR2(255 CHAR),
    EXISTING_FACILITY_EMAIL VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CREDIT_FACILITY_TEMPLATE PRIMARY KEY (CREDIT_FACILITY_TEMPLATE_ID)
);

CREATE TABLE T_CREDIT_FACILITY_TEMPLATE_AUD (
    ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    CREDIT_FACILITY_TYPE_ID NUMBER(10),
    CREDIT_FACILITY_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    MAXIMUM_FACILITY_AMOUNT NUMBER(19,2),
    MINIMUM_FACILITY_AMOUNT NUMBER(19,2),
    SHOW_PURPOSE VARCHAR2(50 CHAR),
    SHOW_REPAYMENT VARCHAR2(50 CHAR),
    SHOW_CONDITION VARCHAR2(50 CHAR),
    SHOW_REMARK VARCHAR2(50 CHAR),
    SHOW_CALCULATOR VARCHAR2(50 CHAR),
    SHOW_RENTAL_DATA VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    NEW_FACILITY_EMAIL VARCHAR2(255 CHAR),
    EXISTING_FACILITY_EMAIL VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CREDIT_FACILITY_TEMPLATE_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CREDIT_FACILITY_TEMPLATE_TEMP (
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TYPE_ID NUMBER(10),
    CREDIT_FACILITY_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    MAXIMUM_FACILITY_AMOUNT NUMBER(19,2),
    MINIMUM_FACILITY_AMOUNT NUMBER(19,2),
    SHOW_PURPOSE VARCHAR2(50 CHAR),
    SHOW_REPAYMENT VARCHAR2(50 CHAR),
    SHOW_CONDITION VARCHAR2(50 CHAR),
    SHOW_REMARK VARCHAR2(50 CHAR),
    SHOW_CALCULATOR VARCHAR2(50 CHAR),
    SHOW_RENTAL_DATA VARCHAR2(50 CHAR),
    STATUS VARCHAR2(50 CHAR),
    NEW_FACILITY_EMAIL VARCHAR2(255 CHAR),
    EXISTING_FACILITY_EMAIL VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CREDIT_FACILITY_TEMPLATE_TEMP PRIMARY KEY (CREDIT_FACILITY_TEMPLATE_ID)
);

CREATE TABLE T_CREDIT_FACILITY_TYPE (
    CREDIT_FACILITY_TYPE_ID NUMBER(10) NOT NULL,
    FACILITY_TYPE_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CREDIT_FACILITY_TYPE PRIMARY KEY (CREDIT_FACILITY_TYPE_ID)
);

CREATE TABLE T_CREDIT_FACILITY_TYPE_AUD (
    ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TYPE_ID NUMBER(10),
    FACILITY_TYPE_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CREDIT_FACILITY_TYPE_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_CREDIT_FACILITY_TYPE_TEMP (
    CREDIT_FACILITY_TYPE_ID NUMBER(10) NOT NULL,
    FACILITY_TYPE_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_CREDIT_FACILITY_TYPE_TEMP PRIMARY KEY (CREDIT_FACILITY_TYPE_ID)
);

CREATE TABLE T_FACILITY_DOCUMENT_ELEMENT (
    ELEMENT_ID NUMBER(10) NOT NULL,
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_TEMP_ID NUMBER(10),
    CREDIT_FACILITY_NAME VARCHAR2(255 CHAR),
    PARENT_ID NUMBER(10),
    ELEMENT_NAME VARCHAR2(255 CHAR),
    ELEMENT_TYPE VARCHAR2(255 CHAR),
    FACILITY_TYPE_ID NUMBER(10),
    IS_NEW VARCHAR2(255 CHAR),
    DOCUMENT_CONTENT VARCHAR2(255 CHAR),
    KEY VARCHAR2(255 CHAR),
    STATUS VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_FACILITY_DOCUMENT_ELEMENT PRIMARY KEY (ELEMENT_ID)
);

CREATE TABLE T_FACILITY_SECURITY_DOCUMENT (
    SECURITY_DOCUMENT_ID NUMBER(10) NOT NULL,
    ELEMENT_ID NUMBER(10),
    FACILITY_PAPER_ID NUMBER(10),
    FACILITY_ID NUMBER(10),
    CREDIT_FACILITY_TEMPLATE_ID NUMBER(10),
    CREDIT_FACILITY_NAME VARCHAR2(255 CHAR),
    DOCUMENT_NAME VARCHAR2(255 CHAR),
    DOCUMENT_CONTENT VARCHAR2(255 CHAR),
    SAVED_BY VARCHAR2(255 CHAR),
    PRINTED_BY VARCHAR2(255 CHAR),
    SAVED_BY_DIV VARCHAR2(255 CHAR),
    AUTH_BY_DIV VARCHAR2(255 CHAR),
    SAVED_DATE TIMESTAMP,
    PRINTED_DATE TIMESTAMP,
    RETURN_COMMENT VARCHAR2(255 CHAR),
    AUTH_BY VARCHAR2(255 CHAR),
    AUTH_DATE TIMESTAMP,
    PRINTED_BY_DIV VARCHAR2(255 CHAR),
    SAVED_BY_DISPLAY_NAME VARCHAR2(255 CHAR),
    AUTH_BY_DISPLAY_NAME VARCHAR2(255 CHAR),
    PRINTED_BY_DISPLAY_NAME VARCHAR2(255 CHAR),
    DOCUMENT_STATUS VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_FACILITY_SECURITY_DOCUMENT PRIMARY KEY (SECURITY_DOCUMENT_ID)
);

CREATE TABLE T_PRIVILEGE (
    PRIVILEGE_ID NUMBER(10) NOT NULL,
    PRIVILEGE_NAME VARCHAR2(255 CHAR),
    PRIVILEGE_CODE VARCHAR2(255 CHAR),
    BEHAVIOUR_DESCRIPTION VARCHAR2(255 CHAR),
    PRIVILEGE_CATEGORY_ID NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    CONSTRAINT PK_T_PRIVILEGE PRIMARY KEY (PRIVILEGE_ID)
);

CREATE TABLE T_PRIVILEGE_CATEGORY (
    PRIVILEGE_CATEGORY_ID NUMBER(10) NOT NULL,
    CATEGORY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_PRIVILEGE_CATEGORY PRIMARY KEY (PRIVILEGE_CATEGORY_ID)
);

CREATE TABLE T_ROLE (
    ROLE_ID NUMBER(10) NOT NULL,
    ROLE_NAME VARCHAR2(255 CHAR),
    UPM_PRIVILAGE_CODE VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_ROLE PRIMARY KEY (ROLE_ID)
);

CREATE TABLE T_ROLE_PRIVILEGE (
    ROLE_ID NUMBER(10) NOT NULL,
    PRIVILEGE_ID NUMBER(10) NOT NULL,
    CONSTRAINT PK_T_ROLE_PRIVILEGE PRIMARY KEY (ROLE_ID, PRIVILEGE_ID)
);

CREATE TABLE T_ROLE_PRIVILEGE_AUD (
    ID NUMBER(10) NOT NULL,
    ROLE_AUD_ID NUMBER(10) NOT NULL,
    PRIVILEGE_ID NUMBER(10) NOT NULL,
    ACTION_DATE TIMESTAMP NOT NULL,
    CONSTRAINT PK_T_ROLE_PRIVILEGE_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_ROLE_PRIVILEGE_TEMP (
    ROLE_ID NUMBER(10) NOT NULL,
    PRIVILEGE_ID NUMBER(10) NOT NULL,
    CONSTRAINT PK_T_ROLE_PRIVILEGE_TEMP PRIMARY KEY (ROLE_ID, PRIVILEGE_ID)
);

CREATE TABLE T_ROLE_TEMP (
    ROLE_ID NUMBER(10) NOT NULL,
    ROLE_NAME VARCHAR2(255 CHAR),
    UPM_PRIVILAGE_CODE VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_ROLE_TEMP PRIMARY KEY (ROLE_ID)
);

CREATE TABLE T_ROLES_AUD (
    ID NUMBER(10) NOT NULL,
    ROLE_ID NUMBER(10) NOT NULL,
    ROLE_NAME VARCHAR2(255 CHAR),
    UPM_PRIVILAGE_CODE VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_ROLES_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_SECURITY_DOCUMENT_TAG_DATA (
    TAG_ID NUMBER(10) NOT NULL,
    SECURITY_DOCUMENT_ID NUMBER(10),
    TAG_ORDER NUMBER(10),
    TAG VARCHAR2(255 CHAR),
    TAG_VALUE VARCHAR2(255 CHAR),
    TAG_TYPE VARCHAR2(255 CHAR),
    FIELD_TYPE VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_SECURITY_DOCUMENT_TAG_DATA PRIMARY KEY (TAG_ID)
);

CREATE TABLE T_SUPPORTING_DOC (
    SUPPORTING_DOC_ID NUMBER(10) NOT NULL,
    DOCUMENT_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    SUPPORT_DOCUMENT_TYPE VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_SUPPORTING_DOC PRIMARY KEY (SUPPORTING_DOC_ID)
);

CREATE TABLE T_SUPPORTING_DOC_AUD (
    ID NUMBER(10) NOT NULL,
    SUPPORTING_DOC_ID NUMBER(10) NOT NULL,
    DOCUMENT_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    SUPPORT_DOCUMENT_TYPE VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_SUPPORTING_DOC_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_SUPPORTING_DOC_TEMP (
    SUPPORTING_DOC_ID NUMBER(10) NOT NULL,
    DOCUMENT_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    SUPPORT_DOCUMENT_TYPE VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_SUPPORTING_DOC_TEMP PRIMARY KEY (SUPPORTING_DOC_ID)
);

CREATE TABLE T_UPC_SECTION (
    UPC_SECTION_ID NUMBER(10) NOT NULL,
    UPC_SECTION_NAME VARCHAR2(255 CHAR),
    UPC_SECTION_DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPC_SECTION PRIMARY KEY (UPC_SECTION_ID)
);

CREATE TABLE T_UPC_SECTION_AUD (
    ID NUMBER(10) NOT NULL,
    UPC_SECTION_ID NUMBER(10) NOT NULL,
    UPC_SECTION_NAME VARCHAR2(255 CHAR),
    UPC_SECTION_DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPC_SECTION_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_UPC_SECTION_TEMP (
    UPC_SECTION_ID NUMBER(10) NOT NULL,
    UPC_SECTION_NAME VARCHAR2(255 CHAR),
    UPC_SECTION_DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPC_SECTION_TEMP PRIMARY KEY (UPC_SECTION_ID)
);

CREATE TABLE T_UPC_TEMPLATE (
    UPC_TEMPLATE_ID NUMBER(10) NOT NULL,
    TEMPLATE_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    UPC_LABEL VARCHAR2(255 CHAR),
    UPC_LABEL_BACKGROUND_COLOR VARCHAR2(255 CHAR),
    UPC_LABEL_FONT_COLOR VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPC_TEMPLATE PRIMARY KEY (UPC_TEMPLATE_ID)
);

CREATE TABLE T_UPC_TEMPLATE_AUD (
    ID NUMBER(10) NOT NULL,
    UPC_TEMPLATE_ID NUMBER(10),
    TEMPLATE_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    UPC_LABEL VARCHAR2(255 CHAR),
    UPC_LABEL_BACKGROUND_COLOR VARCHAR2(255 CHAR),
    UPC_LABEL_FONT_COLOR VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    ACTION_BY VARCHAR2(255 CHAR),
    ACTION_DATE TIMESTAMP,
    ACTION_MSG VARCHAR2(255 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPC_TEMPLATE_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_UPC_TEMPLATE_DATA (
    UPC_TEMPLATE_DATA_ID NUMBER(10) NOT NULL,
    UPC_TEMPLATE_ID NUMBER(10),
    UPC_SECTION_ID NUMBER(10),
    PARENT_SECTION_ID NUMBER(10),
    SECTION_LEVEL NUMBER(10),
    DISPLAY_ORDER NUMBER(10),
    CONSTRAINT PK_T_UPC_TEMPLATE_DATA PRIMARY KEY (UPC_TEMPLATE_DATA_ID)
);

CREATE TABLE T_UPC_TEMPLATE_DATA_AUD (
    ID NUMBER(10) NOT NULL,
    UPC_TEMPLATE_DATA_ID NUMBER(10),
    UPC_TEMPLATE_ID NUMBER(10),
    UPC_SECTION_ID NUMBER(10),
    PARENT_SECTION_ID NUMBER(10),
    SECTION_LEVEL NUMBER(10),
    DISPLAY_ORDER NUMBER(10),
    CONSTRAINT PK_T_UPC_TEMPLATE_DATA_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_UPC_TEMPLATE_DATA_TEMP (
    UPC_TEMPLATE_DATA_ID NUMBER(10) NOT NULL,
    UPC_TEMPLATE_ID NUMBER(10),
    UPC_SECTION_ID NUMBER(10),
    PARENT_SECTION_ID NUMBER(10),
    SECTION_LEVEL NUMBER(10),
    DISPLAY_ORDER NUMBER(10),
    CONSTRAINT PK_T_UPC_TEMPLATE_DATA_TEMP PRIMARY KEY (UPC_TEMPLATE_DATA_ID)
);

CREATE TABLE T_UPC_TEMPLATE_TEMP (
    UPC_TEMPLATE_ID NUMBER(10) NOT NULL,
    TEMPLATE_NAME VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    UPC_LABEL VARCHAR2(255 CHAR),
    UPC_LABEL_BACKGROUND_COLOR VARCHAR2(255 CHAR),
    UPC_LABEL_FONT_COLOR VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPC_TEMPLATE_TEMP PRIMARY KEY (UPC_TEMPLATE_ID)
);

CREATE TABLE T_UPM_GROUP (
    UPM_GROUP_ID NUMBER(10) NOT NULL,
    GROUP_CODE VARCHAR2(255 CHAR),
    REFERENCE_NAME VARCHAR2(255 CHAR),
    WORK_FLOW_LEVEL NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPM_GROUP PRIMARY KEY (UPM_GROUP_ID)
);

CREATE TABLE T_UPM_GROUP_TEMP (
    UPM_GROUP_ID NUMBER(10) NOT NULL,
    GROUP_CODE VARCHAR2(255 CHAR),
    REFERENCE_NAME VARCHAR2(255 CHAR),
    WORK_FLOW_LEVEL NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPM_GROUP_TEMP PRIMARY KEY (UPM_GROUP_ID)
);

CREATE TABLE T_UPM_GROUP_TEMP_AUD (
    REV NUMBER(10) NOT NULL,
    REVTYPE NUMBER(10) NOT NULL,
    UPM_GROUP_ID NUMBER(10) NOT NULL,
    GROUP_CODE VARCHAR2(255 CHAR),
    REFERENCE_NAME VARCHAR2(255 CHAR),
    WORK_FLOW_LEVEL NUMBER(10),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_UPM_GROUP_TEMP_AUD PRIMARY KEY (REV)
);

CREATE TABLE T_USER_DA (
    USER_DA_ID NUMBER(10) NOT NULL,
    USER_NAME VARCHAR2(255 CHAR),
    MAX_AMOUNT NUMBER(19,2),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_USER_DA PRIMARY KEY (USER_DA_ID)
);

CREATE TABLE T_USER_DA_AUD (
    ID NUMBER(10) NOT NULL,
    USER_DA_ID NUMBER(10) NOT NULL,
    USER_NAME VARCHAR2(255 CHAR),
    MAX_AMOUNT NUMBER(19,2),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_USER_DA_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_USER_DA_TEMP (
    USER_DA_ID NUMBER(10) NOT NULL,
    USER_NAME VARCHAR2(255 CHAR),
    MAX_AMOUNT NUMBER(19,2),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_USER_DA_TEMP PRIMARY KEY (USER_DA_ID)
);

CREATE TABLE T_WORK_FLOW_TEMPLATE (
    WORK_FLOW_TEMPLATE_ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_NAME VARCHAR2(255 CHAR),
    CODE VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_WORK_FLOW_TEMPLATE PRIMARY KEY (WORK_FLOW_TEMPLATE_ID)
);

CREATE TABLE T_WORK_FLOW_TEMPLATE_DATA (
    WORK_FLOW_TEMPLATE_DATA_ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_ID NUMBER(10),
    UPM_GROUP_ID NUMBER(10),
    NEXT_UPM_GROUP_ID NUMBER(10),
    PREVIOUS_UPM_GROUP_ID NUMBER(10),
    DISPLAY_ORDER NUMBER(10),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_WORK_FLOW_TEMPLATE_DATA PRIMARY KEY (WORK_FLOW_TEMPLATE_DATA_ID)
);

CREATE TABLE T_WORK_FLOW_TEMPLATE_DATA_AUD (
    ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_DATA_ID NUMBER(10),
    NEXT_UPM_GROUP_ID NUMBER(10),
    PREVIOUS_UPM_GROUP_ID NUMBER(10),
    UPM_GROUP_ID NUMBER(10),
    WORK_FLOW_TEMPLATE_ID NUMBER(10),
    DISPLAY_ORDER NUMBER(10),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_WORK_FLOW_TEMPLATE_DATA_AUD PRIMARY KEY (ID)
);

CREATE TABLE T_WORK_FLOW_TEMPLATE_DATA_TEMP (
    WORK_FLOW_TEMPLATE_DATA_ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_ID NUMBER(10),
    UPM_GROUP_ID NUMBER(10),
    NEXT_UPM_GROUP_ID NUMBER(10),
    PREVIOUS_UPM_GROUP_ID NUMBER(10),
    DISPLAY_ORDER NUMBER(10),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_WORK_FLOW_TEMPLATE_DATA_TEMP PRIMARY KEY (WORK_FLOW_TEMPLATE_DATA_ID)
);

CREATE TABLE T_WORK_FLOW_TEMPLATE_TEMP (
    WORK_FLOW_TEMPLATE_ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_NAME VARCHAR2(255 CHAR),
    CODE VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_WORK_FLOW_TEMPLATE_TEMP PRIMARY KEY (WORK_FLOW_TEMPLATE_ID)
);

CREATE TABLE T_WORKFLOW_TEMPLATE_AUD (
    ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_ID NUMBER(10) NOT NULL,
    WORK_FLOW_TEMPLATE_NAME VARCHAR2(255 CHAR),
    CODE VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(255 CHAR),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR2(255 CHAR),
    APPROVE_STATUS VARCHAR2(50 CHAR),
    APPROVED_DATE TIMESTAMP,
    APPROVED_BY VARCHAR2(255 CHAR),
    CONSTRAINT PK_T_WORKFLOW_TEMPLATE_AUD PRIMARY KEY (ID)
);


================================================================================================================================================
=============================================================     NEW    =======================================================================
================================================================================================================================================

--------------------------
/*-- 1. UPC_SECTION --*/
--------------------------

CREATE TABLE CASV3_T_UPC_SECTION_AUD AS
SELECT *
FROM T_UPC_SECTION;


DELETE FROM T_UPC_SECTION s
WHERE (s.approve_status <> 'APPROVED'
   OR s.status <> 'ACT')

AND NOT EXISTS (
    SELECT 1
    FROM T_FP_UPC_SECTION_DATA d
    WHERE d.UPC_SECTION_ID = s.UPC_SECTION_ID
)

AND NOT EXISTS (
    SELECT 1
    FROM T_UPC_TEMPLATE_DATA t
    WHERE t.UPC_SECTION_ID = s.UPC_SECTION_ID
);